### ISSUE TITLE
Auth not working

### ISSUE THREAD

**Issue by gtie** [panholt/sparkpy#8]
```
Python 3.6.1 (default, Sep  7 2017, 16:36:03)
[GCC 6.3.0 20170406] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sparkpy import Spark
>>> spark = Spark('<my bot token>')
>>> spark.me
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/.../.virtualenvs/dbot36/lib/python3.6/site-packages/sparkpy/spark.py", line 88, in me
    self._fetch_self()
  File "/home/.../.virtualenvs/dbot36/lib/python3.6/site-packages/sparkpy/spark.py", line 167, in _fetch_self
    if resp.status_code == 200:
Exception: Invalid status code 401:
```

**Comment by gtie** [comment]
All good actually... got the wrong token.
